/**
 * Central replacement library for phrase and word rewrites.
 *
 * Why keep this separate:
 * - easier to add more replacements later
 * - safer debugging
 * - keeps textTools.ts focused on logic, not huge data lists
 *
 * How to use:
 * - import PHRASE_REPLACEMENTS and WORD_REPLACEMENTS into textTools.ts
 * - apply phrase replacements first
 * - apply word replacements second
 */

export const PHRASE_REPLACEMENTS: Array<[RegExp, string]> = [
  // General AI-style filler
  [/\bit is important to note that\b/gi, ""],
  [/\bit should be noted that\b/gi, ""],
  [/\bin many cases\b/gi, "often"],
  [/\bmore specifically\b/gi, "in particular"],
  [/\bneedless to say\b/gi, ""],
  [/\bit can be said that\b/gi, ""],
  [/\bthis means that\b/gi, "so"],
  [/\ba wide range of\b/gi, "many"],
  [/\bplays an important role\b/gi, "helps a lot"],
  [/\bplays a vital role\b/gi, "is important"],
  [/\bwithout a doubt\b/gi, "clearly"],
  [/\bin conclusion\b/gi, "overall"],
  [/\bto conclude\b/gi, "overall"],
  [/\bin essence\b/gi, "overall"],

  // Repetition breakers
  [/\bthe same code again and again\b/gi, "the same code multiple times"],
  [/\binstead of writing the same code again and again\b/gi, "rather than repeating the same code multiple times"],
  [/\binstead of\b/gi, "rather than"],
  [/\bagain and again\b/gi, "repeatedly"],
  [/\bover and over again\b/gi, "repeatedly"],

  // Technical / software writing
  [/\bused to build\b/gi, "used to create"],
  [/\bused to develop\b/gi, "used to create"],
  [/\bused to make\b/gi, "used to create"],
  [/\bcan be combined with other tools and libraries\b/gi, "can also work with other tools and libraries"],
  [/\bmakes the code easier to manage and understand\b/gi, "makes the code easier to maintain and read"],
  [/\bhelps keep the application predictable and easier to debug\b/gi, "makes the application more predictable and easier to debug"],
  [/\bimproves performance by updating only the parts of the page that change instead of reloading the whole page\b/gi, "improves performance because only the changed parts of the page update instead of the whole page reloading"],
  [/\bone of the main reasons\b/gi, "a main reason"],
  [/\bis widely used because it makes\b/gi, "is popular because it makes"],
  [/\bfrontend development more efficient and organized\b/gi, "frontend development more efficient and organized"],
  [/\bcan also be combined with other tools\b/gi, "can also work with other tools"],
  [/\bstrong community support\b/gi, "solid community support"],
  [/\bbecause of its flexibility\b/gi, "thanks to its flexibility"],
  [/\bhas become one of the most important technologies\b/gi, "has become one of the key technologies"],

  // Programming / Java / general tech
  [/\bplatform-independent\b/gi, "able to run across platforms"],
  [/\bwithout major changes\b/gi, "without major modifications"],
  [/\bdue to this feature\b/gi, "because of this"],
  [/\bbuilding software that works in many environments\b/gi, "building software that runs across many environments"],
  [/\bone major use of\b/gi, "one common use of"],
  [/\bis also commonly used in\b/gi, "is also widely used in"],
  [/\bcommonly called\b/gi, "commonly known as"],
  [/\bbecame very popular for building software\b/gi, "became popular for building software"],
  [/\bstrong in handling large, complex applications\b/gi, "good at handling large and complex applications"],
  [/\btrusted by many organizations around the world\b/gi, "trusted by many organizations worldwide"],

  // Academic / report style
  [/\bthis report aims to\b/gi, "this report examines"],
  [/\bthis essay aims to\b/gi, "this essay examines"],
  [/\bthis study aims to\b/gi, "this study examines"],
  [/\bit is evident that\b/gi, "it is clear that"],
  [/\bdue to the fact that\b/gi, "because"],
  [/\bon the other hand\b/gi, "in contrast"],
  [/\bas a result of\b/gi, "because of"],
  [/\bin relation to\b/gi, "about"],
  [/\bwith regard to\b/gi, "about"],
  [/\bfor the purpose of\b/gi, "for"],
  [/\bat this point in time\b/gi, "now"],
  [/\bin the event that\b/gi, "if"],

  // SOP / personal writing
  [/\bI have a strong interest in\b/gi, "I am strongly interested in"],
  [/\bI am passionate about\b/gi, "I care deeply about"],
  [/\bI would like to pursue\b/gi, "I want to pursue"],
  [/\bthis opportunity will help me\b/gi, "this opportunity would help me"],
  [/\bI believe that this program will\b/gi, "I believe this program will"],
  [/\bI have gained valuable experience in\b/gi, "I have gained experience in"],
  [/\bplayed an important role in shaping my interest\b/gi, "helped shape my interest"],
  [/\bhas motivated me to\b/gi, "has pushed me to"],
  [/\bI am eager to contribute to\b/gi, "I am ready to contribute to"],
  [/\bI look forward to contributing to\b/gi, "I hope to contribute to"],

  // Workplace / business writing
  [/\bI am writing to inform you that\b/gi, "I’m writing to let you know that"],
  [/\bplease be informed that\b/gi, "please note that"],
  [/\bkindly note that\b/gi, "please note that"],
  [/\bat your earliest convenience\b/gi, "when you can"],
  [/\bshould you have any questions\b/gi, "if you have any questions"],
  [/\bdo not hesitate to contact me\b/gi, "feel free to contact me"],
  [/\bthank you for your understanding\b/gi, "thanks for your understanding"],
  [/\bI would appreciate it if\b/gi, "I’d appreciate it if"],
  [/\bfor further information\b/gi, "for more information"],
  [/\bwith reference to\b/gi, "regarding"],

  // Education / healthcare / general factual writing
  [/\bplays a major role in\b/gi, "plays a big role in"],
  [/\bhelps people recover from illness or injury\b/gi, "helps people recover from illness and injury"],
  [/\bis not only about\b/gi, "is not just about"],
  [/\bmaking sure patients feel safe and comfortable during treatment\b/gi, "helping patients feel safe and comfortable during treatment"],
  [/\bstrong communication skills\b/gi, "good communication skills"],
  [/\bhelp educate families about treatment plans and healthy living\b/gi, "help families understand treatment plans and healthy living"],
  [/\bbecause of their dedication\b/gi, "because of that dedication"],
  [/\btheir work is essential in improving health\b/gi, "their work is essential to better health"],
  // Extra general filler / robotic phrasing
[/\bit is worth mentioning that\b/gi, ""],
[/\bit is worth noting that\b/gi, ""],
[/\bit is clear that\b/gi, "clearly,"],
[/\bit is evident that\b/gi, "clearly,"],
[/\bit is undeniable that\b/gi, "clearly,"],
[/\bfrom this perspective\b/gi, "from this view"],
[/\bin this context\b/gi, "here"],
[/\bin this regard\b/gi, "here"],
[/\bas mentioned earlier\b/gi, "as noted earlier"],
[/\bin other words\b/gi, "put simply"],
[/\bfor example\b/gi, "for instance"],
[/\bfor instance\b/gi, "for example"],
[/\bin addition\b/gi, "also"],
[/\bfurthermore\b/gi, "also"],
[/\bmoreover\b/gi, "also"],
[/\badditionally\b/gi, "also"],
[/\bon top of that\b/gi, "also"],
[/\bin summary\b/gi, "overall"],
[/\bto sum up\b/gi, "overall"],
[/\ball things considered\b/gi, "overall"],

// Common copied-block breakers
[/\bis known for being\b/gi, "is known to be"],
[/\bhas become very popular\b/gi, "has become popular"],
[/\bis widely known for\b/gi, "is known for"],
[/\bis often used for\b/gi, "is commonly used for"],
[/\bis mainly used for\b/gi, "is mostly used for"],
[/\bcan be used in many different areas\b/gi, "can be used in many areas"],
[/\bused in many different industries\b/gi, "used across many industries"],
[/\bhas many different uses\b/gi, "has many uses"],
[/\bcan help users\b/gi, "can help people"],
[/\bthis helps developers\b/gi, "this helps developers"],
[/\bthis helps users\b/gi, "this helps users"],
[/\bthis allows developers to\b/gi, "this lets developers"],
[/\bthis allows users to\b/gi, "this lets users"],

// Technical / software explanations
[/\bhelps developers make fast, interactive, and reusable UI components\b/gi, "helps developers create fast, interactive, and reusable UI components"],
[/\bbreak the interface into small parts called components\b/gi, "divide the interface into smaller units called components"],
[/\bhelps keep the application predictable and easier to debug\b/gi, "helps make the application more predictable and easier to debug"],
[/\bcan run on different operating systems\b/gi, "can run on different operating systems"],
[/\bwithout significant modifications\b/gi, "without major modifications"],
[/\bcommonly referred to as\b/gi, "commonly known as"],
[/\bgained a lot of popularity\b/gi, "became popular"],
[/\bcompatible with numerous environments\b/gi, "usable across many environments"],
[/\bonline services\b/gi, "web services"],
[/\bbackend systems for websites\b/gi, "backend systems for websites"],
[/\bmobile applications for smartphones and tablets\b/gi, "mobile apps for smartphones and tablets"],
[/\bdeal with large and complex applications\b/gi, "handle large and complex applications"],
[/\btrusted in many organizations worldwide\b/gi, "trusted by many organizations worldwide"],
[/\bgood libraries\b/gi, "strong libraries"],
[/\bbroad spectrums of applications\b/gi, "a wide range of applications"],

// Plain-English replacements for factual writing
[/\bis reputed to be\b/gi, "is known to be"],
[/\bmade platform-independent\b/gi, "designed to work across platforms"],
[/\bexecute on other operating systems\b/gi, "run on other operating systems"],
[/\bwithout significant modifications\b/gi, "without major modifications"],
[/\bthis can be done since\b/gi, "this works because"],
[/\bweb online services\b/gi, "online services"],
[/\bwhereby developers are developing\b/gi, "where developers create"],
[/\bhas a strong ability to deal with\b/gi, "is good at handling"],
[/\bthis is the reason why\b/gi, "which is why"],
[/\bapplicable in the education field\b/gi, "used in education"],
[/\binstructs relevant concepts of programming\b/gi, "teaches important programming concepts"],
[/\benable it to be an asset to\b/gi, "make it useful for"],
[/\bnew-comers and professional developers\b/gi, "beginners and professional developers"],

// Academic / report cleanup
[/\bthis paper discusses\b/gi, "this paper examines"],
[/\bthis section discusses\b/gi, "this section examines"],
[/\bthe findings indicate that\b/gi, "the findings show that"],
[/\bthe results demonstrate that\b/gi, "the results show that"],
[/\bit can therefore be argued that\b/gi, "it can therefore be said that"],
[/\bas discussed above\b/gi, "as discussed earlier"],
[/\bin light of this\b/gi, "because of this"],
[/\bwith this in mind\b/gi, "keeping this in mind"],
[/\bit is necessary to\b/gi, "it is important to"],
[/\bit is possible to see that\b/gi, "it is clear that"],
[/\ba large number of\b/gi, "many"],
[/\ba significant number of\b/gi, "many"],

// SOP / personal writing cleanup
[/\bI have always been interested in\b/gi, "I have long been interested in"],
[/\bI have always had a strong interest in\b/gi, "I have long had a strong interest in"],
[/\bthis field has always fascinated me\b/gi, "this field has long interested me"],
[/\bI am confident that this program will\b/gi, "I believe this program will"],
[/\bI strongly believe that\b/gi, "I believe that"],
[/\bthis experience has given me the opportunity to\b/gi, "this experience allowed me to"],
[/\bhas provided me with valuable experience in\b/gi, "gave me experience in"],
[/\bI wish to further develop my skills in\b/gi, "I want to further develop my skills in"],
[/\bI hope to make a meaningful contribution to\b/gi, "I hope to contribute meaningfully to"],

// Workplace / email / professional writing
[/\bI am reaching out to\b/gi, "I’m reaching out to"],
[/\bI would like to kindly request\b/gi, "I’d like to request"],
[/\bplease let me know if\b/gi, "let me know if"],
[/\bI wanted to follow up on\b/gi, "I’m following up on"],
[/\bwith respect to\b/gi, "about"],
[/\bas per your request\b/gi, "as requested"],
[/\bfor your reference\b/gi, "for reference"],
[/\bplease feel free to reach out\b/gi, "feel free to reach out"],
[/\bI look forward to hearing from you\b/gi, "I look forward to hearing from you"],
[/\bthank you for taking the time to\b/gi, "thanks for taking the time to"],

// Healthcare / education / general explanatory writing
[/\bplays a key role in\b/gi, "plays a major role in"],
[/\bhelps improve patient outcomes\b/gi, "helps improve patient outcomes"],
[/\bensure patients feel safe and comfortable\b/gi, "help patients feel safe and comfortable"],
[/\brespond quickly in emergencies\b/gi, "respond quickly in emergencies"],
[/\bteaches important concepts such as\b/gi, "teaches important concepts like"],
[/\bis useful for both beginners and professionals\b/gi, "is useful for both beginners and professionals"],
// More general phrase replacements
[/\bit is commonly known that\b/gi, "it is widely known that"],
[/\bit is widely believed that\b/gi, "many people believe that"],
[/\bit is easy to see that\b/gi, "it is clear that"],
[/\bit is true that\b/gi, "it is true that"],
[/\bthis can be seen in\b/gi, "this appears in"],
[/\bthis can be observed in\b/gi, "this appears in"],
[/\bthis can be explained by\b/gi, "this happens because"],
[/\bthis shows that\b/gi, "this suggests that"],
[/\bthis highlights the fact that\b/gi, "this highlights that"],
[/\bthis demonstrates that\b/gi, "this shows that"],
[/\bin the same way\b/gi, "similarly"],
[/\bin a similar way\b/gi, "similarly"],
[/\bin contrast to this\b/gi, "by contrast"],
[/\bon the contrary\b/gi, "by contrast"],
[/\bin most cases\b/gi, "usually"],
[/\bin some cases\b/gi, "sometimes"],
[/\bas previously mentioned\b/gi, "as mentioned earlier"],
[/\bas stated earlier\b/gi, "as noted earlier"],
[/\bin simple terms\b/gi, "simply"],
[/\bfor this reason\b/gi, "because of this"],

// Stronger copied-block breakers
[/\bknown for being\b/gi, "known to be"],
[/\bdesigned to be\b/gi, "designed to"],
[/\bhas the ability to\b/gi, "can"],
[/\bis able to\b/gi, "can"],
[/\bis useful for\b/gi, "helps with"],
[/\bis beneficial for\b/gi, "helps"],
[/\bhas become popular because\b/gi, "is popular because"],
[/\bhas become widely used because\b/gi, "is widely used because"],
[/\bthis is because\b/gi, "this happens because"],
[/\bas a result\b/gi, "so"],
[/\bdue to this\b/gi, "because of this"],
[/\bdue to the fact that\b/gi, "because"],
[/\bfor that reason\b/gi, "because of that"],
[/\bthanks to this\b/gi, "because of this"],

// Tech / software / programming
[/\bhelps developers create fast, interactive, and reusable UI components\b/gi, "helps developers create fast, interactive, and reusable UI parts"],
[/\bbreak the interface into small parts called components\b/gi, "split the interface into smaller parts called components"],
[/\bonly the parts of the page that change\b/gi, "only the parts of the page that need updating"],
[/\breloading the whole page\b/gi, "reloading the entire page"],
[/\bkeeps the application predictable and easier to debug\b/gi, "makes the application more predictable and easier to debug"],
[/\bcan be used to build\b/gi, "can be used to create"],
[/\bcan be used to develop\b/gi, "can be used to create"],
[/\bworks across many environments\b/gi, "runs across many environments"],
[/\bwidely used in Android app development\b/gi, "widely used in Android development"],
[/\bmobile applications for smartphones and tablets\b/gi, "mobile apps for smartphones and tablets"],
[/\blarge and complex applications\b/gi, "large, complex applications"],
[/\bobject-oriented programming, classes, objects, inheritance, and problem-solving\b/gi, "object-oriented programming, classes, objects, inheritance, and problem-solving skills"],

// Academic / report / thesis
[/\bthis section focuses on\b/gi, "this section looks at"],
[/\bthis chapter focuses on\b/gi, "this chapter looks at"],
[/\bthe purpose of this study is to\b/gi, "this study examines"],
[/\bthe main aim of this study is to\b/gi, "this study mainly examines"],
[/\bthis research seeks to\b/gi, "this research examines"],
[/\bthe results suggest that\b/gi, "the results show that"],
[/\bthe evidence suggests that\b/gi, "the evidence shows that"],
[/\bcan therefore be considered\b/gi, "can therefore be seen as"],
[/\bmay therefore be considered\b/gi, "may therefore be seen as"],
[/\bin terms of\b/gi, "for"],
[/\bwith respect to\b/gi, "for"],
[/\bin relation to\b/gi, "for"],
[/\bthe extent to which\b/gi, "how much"],
[/\ba large proportion of\b/gi, "many"],
[/\ba small proportion of\b/gi, "few"],

// SOP / personal writing
[/\bI have been deeply interested in\b/gi, "I have long been interested in"],
[/\bI have always wanted to\b/gi, "I have long wanted to"],
[/\bthis field has inspired me to\b/gi, "this field has encouraged me to"],
[/\bI have developed a strong interest in\b/gi, "I have developed a clear interest in"],
[/\bI hope to build on my experience in\b/gi, "I hope to build on my experience with"],
[/\bI want to further strengthen my skills in\b/gi, "I want to strengthen my skills in"],
[/\bI believe this opportunity would allow me to\b/gi, "I believe this opportunity would help me"],
[/\bthis experience strengthened my interest in\b/gi, "this experience deepened my interest in"],

// Workplace / formal writing
[/\bplease let me know at your earliest convenience\b/gi, "please let me know when you can"],
[/\bI am following up regarding\b/gi, "I’m following up about"],
[/\bI would like to follow up on\b/gi, "I’d like to follow up on"],
[/\battached for your reference\b/gi, "attached for reference"],
[/\bfor your convenience\b/gi, "for convenience"],
[/\bshould you need any further information\b/gi, "if you need any more information"],
[/\bplease do not hesitate to reach out\b/gi, "feel free to reach out"],
[/\bthank you in advance\b/gi, "thanks in advance"],

// Education / healthcare / explanatory writing
[/\bplays a central role in\b/gi, "plays a major role in"],
[/\bhelps support patients\b/gi, "supports patients"],
[/\bhelping patients feel safe and comfortable during treatment\b/gi, "helping patients feel safe and comfortable during care"],
[/\bresponding quickly in emergencies\b/gi, "responding quickly in emergencies"],
[/\bused in education, desktop software, cloud systems, and game development\b/gi, "used in education, desktop software, cloud systems, and game development projects"],
[/\buseful for both beginners and professional developers\b/gi, "useful for both beginners and experienced developers"],
[/\bused in a variety of applications\b/gi, "used in many applications"],
[/\bused in a wide range of applications\b/gi, "used across many applications"],
[/\bhelps improve efficiency\b/gi, "helps improve efficiency"],
[/\bhelps improve productivity\b/gi, "helps improve productivity"],
[/\bhas become a popular choice\b/gi, "has become a popular option"],
[/\bis a popular choice for\b/gi, "is a common choice for"],
[/\bis known for its ability to\b/gi, "is known for how it can"],
[/\bprovides a way to\b/gi, "makes it possible to"],
[/\boffers a way to\b/gi, "makes it easier to"],
[/\bcan be applied in\b/gi, "can be used in"],
[/\bcan be seen in many areas\b/gi, "appears in many areas"],
[/\bused by many companies\b/gi, "used by many organizations"],
[/\bused by large companies\b/gi, "used by many large companies"],
[/\bhas a large community\b/gi, "has a large user community"],
[/\bcontinues to be widely used\b/gi, "is still widely used"],
[/\bcontinues to play an important role\b/gi, "still plays an important role"],
[/\bis considered one of the most important\b/gi, "is seen as one of the most important"],
[/\bhas remained one of the most important\b/gi, "has remained one of the key"],
[/\bused in both\b/gi, "used in both"],
[/\bfor both beginners and professionals\b/gi, "for beginners and professionals"],
[/\bfor both students and professionals\b/gi, "for students and professionals"],
[/\bthis makes it useful for\b/gi, "that makes it useful for"],
[/\bthis makes it easier for developers to\b/gi, "that makes it easier for developers to"],
[/\bthis allows the system to\b/gi, "that allows the system to"],
[/\bthis feature allows\b/gi, "this feature lets"],
[/\bthis helps explain why\b/gi, "this helps show why"],
[/\bthis is one reason why\b/gi, "this is one reason"],
[/\bthis is another reason why\b/gi, "this is another reason"],
[/\bknown for its flexibility\b/gi, "known for being flexible"],
[/\bknown for its simplicity\b/gi, "known for being simple"],
[/\bknown for its reliability\b/gi, "known for being reliable"],
[/\bused for building\b/gi, "used to build"],
[/\bused for creating\b/gi, "used to create"],
[/\bis still an important part of\b/gi, "is still an important part of"],
[/\bplays a big role in\b/gi, "plays a major role in"],
[/\bhelps explain the importance of\b/gi, "shows the importance of"],
[/\bhas many practical uses\b/gi, "has many practical uses"],
[/\bworks well for\b/gi, "is well suited to"],
[/\bis well suited for\b/gi, "works well for"],

];

export const WORD_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\butilize\b/gi, "use"],
  [/\bindividuals\b/gi, "people"],
  [/\bnumerous\b/gi, "many"],
  [/\bobtain\b/gi, "get"],
  [/\bdemonstrate\b/gi, "show"],
  [/\bregarding\b/gi, "about"],
  [/\bassistance\b/gi, "help"],
  [/\bpurchase\b/gi, "buy"],
  [/\bresidence\b/gi, "home"],
  [/\bcommence\b/gi, "start"],
  [/\bterminate\b/gi, "end"],
  [/\bapproximately\b/gi, "about"],
  [/\bcurrently\b/gi, "now"],
  [/\btherefore\b/gi, "so"],
  [/\bhowever\b/gi, "but"],
  [/\bcrucial\b/gi, "important"],
[/\bessential\b/gi, "important"],
[/\bsubstantial\b/gi, "major"],
[/\brobust\b/gi, "strong"],
[/\bvaluable\b/gi, "useful"],
[/\bfacilitate\b/gi, "help"],
[/\bassistive\b/gi, "helpful"],
[/\boptimize\b/gi, "improve"],
[/\benhance\b/gi, "improve"],
[/\bimplement\b/gi, "use"],
[/\bimplements\b/gi, "uses"],
[/\bleverage\b/gi, "use"],
[/\bstreamline\b/gi, "simplify"],
[/\bstreamlines\b/gi, "simplifies"],
[/\bmaintainable\b/gi, "easy to maintain"],
[/\bintuitive\b/gi, "easy to use"],
[/\bversatile\b/gi, "flexible"],
[/\breliable\b/gi, "dependable"],
[/\bnotion\b/gi, "idea"],
[/\bconceptualize\b/gi, "understand"],
[/\bsubsequently\b/gi, "later"],
[/\bprior to\b/gi, "before"],
[/\bfollowing\b/gi, "after"],
[/\bregardless\b/gi, "no matter"],
[/\bcurrently\b/gi, "now"],
[/\bapproximately\b/gi, "about"],
[/\bdependable\b/gi, "reliable"],
[/\bsimple\b/gi, "straightforward"],
[/\bsecure\b/gi, "safe"],
[/\breliable\b/gi, "dependable"],
[/\bmaintain\b/gi, "manage"],
[/\bmaintaining\b/gi, "managing"],
[/\bmaintained\b/gi, "managed"],
[/\bstreamlined\b/gi, "simplified"],
[/\bsimplifies\b/gi, "makes simpler"],
[/\befficient\b/gi, "effective"],
[/\befficiency\b/gi, "effectiveness"],
[/\bcritical\b/gi, "important"],
[/\bsignificant\b/gi, "important"],
[/\bmajor\b/gi, "key"],
[/\bsubstantial\b/gi, "major"],
[/\bimportant\b/gi, "key"],
[/\bvaluable\b/gi, "useful"],
[/\buseful\b/gi, "helpful"],
[/\bhelpful\b/gi, "useful"],
[/\bstrong\b/gi, "solid"],
[/\bsolid\b/gi, "strong"],
[/\boptimize\b/gi, "improve"],
[/\boptimized\b/gi, "improved"],
[/\benhance\b/gi, "improve"],
[/\benhanced\b/gi, "improved"],
[/\bflexible\b/gi, "adaptable"],
[/\badaptable\b/gi, "flexible"],
[/\bcurrently\b/gi, "now"],
[/\bapproximately\b/gi, "about"],
[/\btherefore\b/gi, "so"],
[/\bhowever\b/gi, "but"],
[/\bthus\b/gi, "so"],
[/\bmoreover\b/gi, "also"],
[/\badditionally\b/gi, "also"],
];